- name: "Ensure vpc state as {{ ec2_state }}"
  include_tasks: "vpc.yaml"

- name: "Ensure state of instance's common resources"
  include_tasks: "instance.yaml"

- name: "Ensure instance's role state"
  include_tasks: "{{ ec2_instance_role }}.yaml"

# add_host only happens in one host...
# inventory refresh is a better alternative
- name: "Refresh inventory"
  run_once: true
  delegate_to: localhost
  changed_when: false
  meta: refresh_inventory

- name: "Wait for connection"
  wait_for_connection:
    
- name: "Ready"
  debug:
    msg: "{{ ec2_instance_name }}: ssh {{ ansible_user }}@{{ ansible_host }} -i keychain/{{ ec2_vpc_name }}"
