---
- name: "Deploy"
  hosts: "{{ environments }}"
  vars:
    ansible_become: true
    ansible_gather_facts: true
  vars_files:
    - "config/environment.yaml"
  roles:
    - role: "deploy"
    - role: "test"
