---
namespace: "victorock"
name: "demopoc"
version: "v0.3a"
authors: 
  - "Victor da Costa @victorobotz:twitter"
description: "Provisioner of Demo Environments"
license: "GPL-3.0-or-later"
tags:
  - "lab"
  - "provision"
  - "cloud"
dependencies:
  - "victorock.tower"
  - "victorock.download"
repository: "https://github.com/victorock/demopoc"