---
- name: "create venvs"
  become: true
  easy_install:
    name: "pip"
    virtualenv: "/var/lib/awx/venv/{{ item }}"
    state: "latest"
  loop:
    - "ansible-cloud-release"
    - "ansible-host-release"
    - "ansible-network-release"

- name: "pip common packages"
  become: true
  pip:
    name: "{{ pip_common_packages }}"
    umask: "0022"
    virtualenv: "/var/lib/awx/venv/{{ item }}"
    state: "latest"
  loop:
    - "ansible"
    - "ansible-cloud-release"
    - "ansible-host-release"
    - "ansible-network-release"

- name: "pip packages required by ansible-cloud-release"
  become: true
  pip:
    name: "{{ pip_cloud_packages }}"
    umask: "0022"
    virtualenv: "/var/lib/awx/venv/ansible-cloud-release"
    state: "latest"

- name: "pip packages required by ansible-host-release"
  become: true
  pip:
    name: "{{ pip_host_packages }}"
    umask: "0022"
    virtualenv: "/var/lib/awx/venv/ansible-host-release"
    state: "latest"

- name: "pip packages required by ansible-network-release"
  become: true
  pip:
    name: "{{ pip_network_packages }}"
    umask: "0022"
    virtualenv: "/var/lib/awx/venv/ansible-host-release"
    state: "latest"

- name: "victorock.tower_config"
  include_role:
    name: "victorock.tower_config"

- name: "victorock.tower_facts"
  include_role:
    name: "victorock.tower_facts"
    tasks_from: "run"
    