---
ansible_network_os: "tmos"
ansible_user: "admin"
ansible_password: "{{ deploy_password }}"
ansible_connection: "local"
ansible_gather_facts: false
ansible_provider:
  server: "{{ ansible_host }}"
  server_port: "{{ ansible_port | default('443') }}"
  user: "{{ ansible_user | default('admin') }}"
  password: "{{ ansible_password }}"
  validate_certs: no
