---
ec2_instance_role: "host"
ec2_instance_type: "t2.large"
# Using lookup because the windows network takes some time to come up...
# By doing this way, we are not dependent of network to setup winrm.
ec2_instance_user_data: |
  <powershell>
  {{ lookup('url', 'https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1', split_lines=False) }}
  $admin = [adsi]("WinNT://./administrator, user")
  $admin.PSBase.Invoke("SetPassword", "{{ deploy_password }}")
  </powershell>
  <persist>true</persist>

ec2_ami:
  name: "Windows_Server-2019-English-Full-Base*"
  architecture: "x86_64"
  owners: "591542846629"

ec2_group: "{{ ec2_vpc_name }}"
ec2_group_rules:
  - proto: -1
    from_port: -1
    to_port: -1
    cidr_ip: 0.0.0.0/0
