---
- name: "Generate extravars"
  template:
    src: "extravars.j2"
    dest: "{{ runner_private_data_dir }}/env/extravars"

- name: "Generate inventory configuration for ec2"
  template:
    src: "aws_ec2.yaml.j2"
    dest: "{{ runner_private_data_dir }}/inventory/{{ ec2_vpc_name }}.aws_ec2.yaml"

- name: "Generate ssh-key"
  shell: "ssh-keygen -t rsa -f keychain/{{ ec2_vpc_name }} -N ''"
  args:
    creates: "{{ runner_private_data_dir }}/project/keychain/{{ ec2_vpc_name }}"

- name: "Copy runner ssh-key"
  copy:
    src: "{{ runner_private_data_dir }}/project/keychain/{{ ec2_vpc_name }}"
    dest: "{{ runner_private_data_dir }}/env/ssh_key"

- name: "Pip install requirements"
  pip:
    name: "git+https://github.com/ansible/ansible-runner"
    state: "latest"

- name: "Solve Galaxy dependencies"
  shell: "{{ lookup('template', 'ansible-galaxy.cli.j2') }}"
  register: galaxy_result
  changed_when: "'was installed successfully' in galaxy_result.stdout"

- name: "Runner"
  shell: "{{ lookup('template', 'ansible-runner.cli.j2') }}"
