---
ec2_region: "eu-central-1"
ec2_vpc_name: "demobox"
ec2_vpc_cidr: "10.1.0.0/16"
ec2_vpc_subnet_mgmt: "{{ ec2_vpc_cidr | ipsubnet(24, 0) }}"
ec2_vpc_subnet_outside: "{{ ec2_vpc_cidr | ipsubnet(24, 1) }}"
ec2_vpc_subnet_inside: "{{ ec2_vpc_cidr | ipsubnet(24, 2) }}"