ec2_instance_role: "host"
ec2_instance_type: "t2.large"
ec2_instance_image: "ami-049951c6a9c02b260"
ec2_group: "{{ ec2_vpc_name }}"
ec2_group_rules:
  - proto: -1
    from_port: -1
    to_port: -1
    cidr_ip: 0.0.0.0/0
