---
- name: "Create Instance: type Host"
  delegate_to: localhost
  vars:
    ec2_ami: "{{ r_ec2_ami_facts.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}"
  ec2_instance:
    aws_access_key: "{{ ec2_aws_access_key | default(omit, True) }}"
    aws_secret_key: "{{ ec2_aws_secret_key | default(omit, True) }}"
    region: "{{ ec2_region }}"
    instance_type: "{{ ec2_instance_type }}"
    image_id: "{{ ec2_ami.image_id }}"
    key_name: "{{ ec2_instance_key }}"
    user_data: "{{ ec2_instance_user_data | default(omit) }}"
    volumes: "{{ ec2_instance_volumes | default(omit) }}"
    network:
      interfaces:
        - "{{ r_ec2_eni_mgmt.interface.id }}"
        - "{{ r_ec2_eni_inside.interface.id }}"
    wait: true
    tags:
      Name: "{{ ec2_instance_name }}"
      Environment: "{{ ec2_vpc_name }}"
      Platform: "{{ ansible_network_os | default('host') }}"
  register: r_ec2_instance
