---
- name: "Create ENI: Outside"
  delegate_to: localhost
  ec2_eni:
    aws_access_key: "{{ ec2_aws_access_key | default(omit, True) }}"
    aws_secret_key: "{{ ec2_aws_secret_key | default(omit, True) }}"
    region: "{{ ec2_region }}"
    device_index: 1
    subnet_id: "{{ r_ec2_vpc_subnet_outside.subnet.id }}"
    security_groups: "{{ r_ec2_group.group_id }}"
    private_ip_address: "{{ ec2_instance_interface.outside.private_ip_address }}"
    delete_on_termination: true
    source_dest_check: false
  register: r_ec2_eni_outside

- name: "Tag ENI: Outside"
  delegate_to: localhost
  ec2_tag:
    aws_access_key: "{{ ec2_aws_access_key | default(omit, True) }}"
    aws_secret_key: "{{ ec2_aws_secret_key | default(omit, True) }}"
    region: "{{ ec2_region }}"
    resource: "{{ r_ec2_eni_outside.interface.id }}"
    tags:
      Name: "{{ ec2_instance_name }}"
      Environment: "{{ ec2_vpc_name }}"
      Zone: "outside"

- name: "Create EIP to ENI: Outside"
  delegate_to: localhost
  ec2_eip:
    aws_access_key: "{{ ec2_aws_access_key | default(omit, True) }}"
    aws_secret_key: "{{ ec2_aws_secret_key | default(omit, True) }}"
    region: "{{ ec2_region }}"
    device_id: "{{ r_ec2_eni_outside.interface.id }}"
    private_ip_address: "{{ ec2_instance_interface.outside.private_ip_address }}"
    in_vpc: true
    release_on_disassociation: true
    reuse_existing_ip_allowed: true
  register: r_ec2_eip_outside

- name: "Tag EIP: Outside"
  delegate_to: localhost
  ec2_tag:
    aws_access_key: "{{ ec2_aws_access_key | default(omit, True) }}"
    aws_secret_key: "{{ ec2_aws_secret_key | default(omit, True) }}"
    region: "{{ ec2_region }}"
    resource: "{{ r_ec2_eip_outside.allocation_id }}"
    tags:
      Name: "{{ ec2_instance_name }}"
      Environment: "{{ ec2_vpc_name }}"
      Zone: "outside"

- name: "Create Instance: type Network"
  delegate_to: localhost
  vars:
    ec2_ami: "{{ r_ec2_ami_facts.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}"
  ec2_instance:
    aws_access_key: "{{ ec2_aws_access_key | default(omit, True) }}"
    aws_secret_key: "{{ ec2_aws_secret_key | default(omit, True) }}"
    region: "{{ ec2_region }}"
    instance_type: "{{ ec2_instance_type }}"
    image_id: "{{ ec2_ami.image_id }}"
    key_name: "{{ ec2_instance_key }}"
    user_data: "{{ ec2_instance_user_data | default(omit) }}"
    network:
      interfaces:
        - "{{ r_ec2_eni_mgmt.interface.id }}"
        - "{{ r_ec2_eni_outside.interface.id }}"
        - "{{ r_ec2_eni_inside.interface.id }}"
    wait: true
    tags:
      Name: "{{ ec2_instance_name }}"
      Environment: "{{ ec2_vpc_name }}"
      Platform: "{{ ansible_network_os | default('network') }}"
  register: r_ec2_instance
