---
# EC2 Region: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regions
ec2_region: "eu-central-1"

# VPC Name
ec2_vpc_name: "refactor"

# Network CIDR
ec2_vpc_cidr: "10.1.0.0/16"

# Default password for deployers to configure appliances (Useful for interaction through the webinterface).
#  NOTE: The ssh-key located in project/keychain/<ec2_vpc_name> is injected by the cloud provider.
deploy_password: "demobox123!"

# Environments:
#  Leave only the environments that you want to Build, Provision and Deploy.
environments:
  - linux
  - nios
  - tower
  - splunk
  - fortios
  - asa
  - panos
  - windows
  - tmos