---
- name: "Gather Instance facts"
  ec2_instance_facts:
    region: "{{ ec2_region }}"
    filters:
      "instance-type": "{{ ec2_instance_type }}"
      "key-name": "{{ ec2_instance_key }}"
      "tag:Name": "{{ ec2_instance_name }}"
      "tag:Environment": "{{ ec2_vpc_name }}"
      "tag:Platform": "{{ ansible_network_os | default('appliance') }}"
  register: ec2_instance_facts

- name: "Release EIPs of mgmt ENI"
  ec2_eip:
    region: "{{ ec2_region }}"
    device_id: "{{ item.instance_id }}"
    private_ip_address: "{{ ec2_instance_interface.mgmt.private_ip_address }}"
    state: "absent"
  loop: "{{ ec2_instance_facts.instances }}"
  loop_control:
    label: "instance: {{ item.tags.Name }} ({{ item.instance_id }})"

- name: "Release EIPs of outside ENI"
  ec2_eip:
    region: "{{ ec2_region }}"
    device_id: "{{ item.instance_id }}"
    private_ip_address: "{{ ec2_instance_interface.outside.private_ip_address }}"
    state: "absent"
  loop: "{{ ec2_instance_facts.instances }}"
  loop_control:
    label: "instance: {{ item.tags.Name }} ({{ item.instance_id }})"

- name: "Terminate Instance"
  ec2_instance:
    region: "{{ ec2_region }}"
    instance_ids: "{{ item.instance_id }}"
    wait: true
    state: "terminated"
  loop: "{{ ec2_instance_facts.instances }}"
  loop_control:
    label: "instance: {{ item.tags.Name }} ({{ item.instance_id }})"
