ec2_instance_role: "network"
ec2_instance_type: "t2.large"
ec2_instance_user_data: |
  #!/bin/bash
  while [[ ! -e '/var/prompt/ps1' ]]; do
    echo -n '.'
    sleep 5
  done 

  while [[ ! -e '/var/prompt/cmiSyncStatus' ]]; do
    echo -n '.'
    sleep 5
  done 

  STATUS=`cat /var/prompt/cmiSyncStatus`
  while [[ ${STATUS}x != 'Standalone'x ]]; do
    echo -n '.'
    sleep 5
    STATUS=`cat /var/prompt/cmiSyncStatus`
  done

  tmsh modify auth user '{{ ansible_user }}' password '{{ deploy_password }}'
  tmsh save /sys config

ec2_ami:
  name: "F5*BIGIP*PAYG*Good 25Mbps*"
  owners: "679593333241"
  architecture: "x86_64"
  # GOOD 25mbps
  product_code: "8esk90vx7v713sa0muq2skw3j"

ec2_group: "{{ ec2_vpc_name }}"
ec2_group_rules:
  - proto: -1
    from_port: -1
    to_port: -1
    cidr_ip: 0.0.0.0/0
