---
- name: "Test tower"
  uri:
    url: "https://localhost/api/v2/ping"
    method: "GET"
    body_format: "json"
    force_basic_auth: true
    url_username: "admin"
    url_password: "{{ deploy_password }}"
    status_code: 200
    validate_certs: false
