---
- name: "Wait for system to become reachable"
  wait_for_connection:
    timeout: 900

- name: "Gather facts"
  ios_facts:

- name: "Deploy ios"
  ios_config:
    src: "config.cfg.j2"

- name: "Flush Handlers"
  meta: flush_handlers
